//! Turn-by-turn guidance for the Lunaway app.
//!
//! The app asks the Lunaway API for a route (Valhalla's answer in the OSRM
//! format), then drives a [`api::engine::Guidance`] with every position fix:
//! Ferrostar's navigation core snaps the vehicle to the route, advances the
//! steps, picks the banner and the spoken instruction, and tells when the
//! vehicle has left the route. The same object checks the part of the route
//! still ahead against road events with the server's corridor rule
//! (`lunaway_domain::routing::corridor`), so a closure the phone learns about
//! while driving is judged the way the server judges a route.
//!
//! [`api`] is what flutter_rust_bridge exposes to Dart; [`session`] holds
//! the logic, testable without the bridge; [`track`] places the fixes
//! along the route's steps, so that a step the vehicle passed between two
//! fixes still ends.

pub mod api;
#[allow(
    unsafe_code,
    missing_docs,
    clippy::all,
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "generated by flutter_rust_bridge_codegen: FFI glue, regenerated, never edited"
)]
mod frb_generated;
pub mod session;
pub mod track;
