//! The GraphQL schema. Resolvers stay thin: the logic lives in the domain and
//! service layers, so the GraphQL library can be replaced without touching it.

use async_graphql::{EmptyMutation, EmptySubscription, Enum, Object, Schema};
use lunaway_domain::PlaceKind;

/// The schema served by the API.
pub type LunawaySchema = Schema<QueryRoot, EmptyMutation, EmptySubscription>;

/// Bounds every query, so one request cannot make the server walk an
/// unbounded graph. Raised only with a measured need.
const MAX_DEPTH: usize = 12;
const MAX_COMPLEXITY: usize = 500;

/// Builds the schema with its limits.
#[must_use]
pub fn build_schema() -> LunawaySchema {
    Schema::build(QueryRoot, EmptyMutation, EmptySubscription)
        .limit_depth(MAX_DEPTH)
        .limit_complexity(MAX_COMPLEXITY)
        .finish()
}

/// Root of every read.
#[derive(Debug, Default)]
pub struct QueryRoot;

#[Object]
impl QueryRoot {
    /// Version of the running API.
    async fn api_version(&self) -> &'static str {
        env!("CARGO_PKG_VERSION")
    }

    /// Every kind of place, in display order.
    async fn place_kinds(&self) -> Vec<GqlPlaceKind> {
        PlaceKind::ALL
            .iter()
            .copied()
            .map(GqlPlaceKind::from)
            .collect()
    }
}

// Mirrors `lunaway_domain::PlaceKind`: the `remote` conversion makes the
// compiler refuse a variant present on one side only.
/// What a place is.
#[derive(Enum, Debug, Copy, Clone, Eq, PartialEq)]
#[graphql(remote = "lunaway_domain::PlaceKind", name = "PlaceKind")]
pub enum GqlPlaceKind {
    /// A dedicated motorhome area, with or without services.
    MotorhomeArea,
    /// Motorhome services without overnight parking.
    ServiceArea,
    /// A campsite.
    Campsite,
    /// A general car park that takes motorhomes.
    Parking,
    /// A spot in nature, away from any facility.
    Nature,
    /// A roadside rest area.
    RestArea,
    /// A picnic area.
    PicnicArea,
    /// A farm, vineyard or producer that hosts motorhomes.
    Farm,
    /// A private host who welcomes travellers on their land.
    Homestay,
    /// A spot reachable with a 4x4 only.
    OffRoad,
    /// A useful stop that is not a place to stay.
    ExtraService,
}

const SDL_HEADER: &str =
    "# Generated by `cargo run -p lunaway-api --bin export-schema` from backend/. Do not edit.\n\n";

/// The content of `schema/lunaway.graphql`: a header, then the schema as SDL.
#[must_use]
pub fn sdl_file() -> String {
    format!("{SDL_HEADER}{}", build_schema().sdl())
}
