[package]
name = "lunaway-api"
description = "Lunaway HTTP and GraphQL API."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
async-graphql.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
flate2.workspace = true
http-body-util.workspace = true
lunaway-auth.workspace = true
lunaway-db.workspace = true
lunaway-domain.workspace = true
lunaway-media.workspace = true
reqwest.workspace = true
rustls.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
lunaway-conflate.workspace = true
lunaway-ingest.workspace = true
p256.workspace = true
sqlx.workspace = true
tempfile.workspace = true
tower.workspace = true

[lints]
workspace = true
