import 'package:flutter/material.dart';
import 'package:lunaway/shared/theme/palette.dart';

/// The two colour schemes, built role by role from the palette rather than
/// generated from a seed: a generated scheme tints every surface with the
/// seed's hue (the lavender of stock Material apps), where Lunaway wants
/// cream by day and navy by night.
abstract final class LunaScheme {
  /// "Aube": cream surfaces, navy text, amber actions, teal accents.
  static const aube = ColorScheme(
    brightness: Brightness.light,
    primary: Palette.lanterne,
    onPrimary: Palette.minuit,
    primaryContainer: Palette.lanterne100,
    onPrimaryContainer: Palette.minuit,
    primaryFixed: Palette.lanterne100,
    primaryFixedDim: Palette.lanterne200,
    onPrimaryFixed: Palette.minuit,
    onPrimaryFixedVariant: Palette.lanterne900,
    secondary: Palette.sarcelleProfonde,
    onSecondary: Palette.creme,
    secondaryContainer: Palette.sarcelle100,
    onSecondaryContainer: Palette.sarcelle900,
    secondaryFixed: Palette.sarcelle100,
    secondaryFixedDim: Palette.sarcelle200,
    onSecondaryFixed: Palette.sarcelle900,
    onSecondaryFixedVariant: Palette.sarcelle800,
    tertiary: Palette.minuit,
    onTertiary: Palette.creme,
    tertiaryContainer: Palette.minuit200,
    onTertiaryContainer: Palette.minuit,
    tertiaryFixed: Palette.minuit200,
    tertiaryFixedDim: Palette.minuit300,
    onTertiaryFixed: Palette.minuit,
    onTertiaryFixedVariant: Palette.minuit700,
    error: Palette.corail800,
    onError: Palette.white,
    errorContainer: Palette.corail100,
    onErrorContainer: Palette.corail900,
    surface: Palette.creme100,
    onSurface: Palette.minuit,
    surfaceDim: Palette.creme500,
    surfaceBright: Palette.creme50,
    surfaceContainerLowest: Palette.creme50,
    surfaceContainerLow: Palette.creme200,
    surfaceContainer: Palette.creme300,
    surfaceContainerHigh: Palette.creme400,
    surfaceContainerHighest: Palette.creme500,
    onSurfaceVariant: Palette.minuit500,
    outline: Palette.minuit400,
    outlineVariant: Palette.creme600,
    shadow: Palette.minuit,
    scrim: Palette.minuit950,
    inverseSurface: Palette.minuit850,
    onInverseSurface: Palette.creme,
    inversePrimary: Palette.lanterne,
    surfaceTint: Colors.transparent,
  );

  /// "Minuit": navy surfaces, cream text, the same amber actions.
  static const minuit = ColorScheme(
    brightness: Brightness.dark,
    primary: Palette.lanterne,
    onPrimary: Palette.minuit,
    primaryContainer: Palette.lanterne900,
    onPrimaryContainer: Palette.lanterne100,
    primaryFixed: Palette.lanterne100,
    primaryFixedDim: Palette.lanterne200,
    onPrimaryFixed: Palette.minuit,
    onPrimaryFixedVariant: Palette.lanterne900,
    secondary: Palette.sarcelle300,
    onSecondary: Palette.sarcelle900,
    secondaryContainer: Palette.sarcelle800,
    onSecondaryContainer: Palette.sarcelle100,
    secondaryFixed: Palette.sarcelle100,
    secondaryFixedDim: Palette.sarcelle200,
    onSecondaryFixed: Palette.sarcelle900,
    onSecondaryFixedVariant: Palette.sarcelle800,
    tertiary: Palette.creme,
    onTertiary: Palette.minuit,
    tertiaryContainer: Palette.minuit700,
    onTertiaryContainer: Palette.creme,
    tertiaryFixed: Palette.minuit200,
    tertiaryFixedDim: Palette.minuit300,
    onTertiaryFixed: Palette.minuit,
    onTertiaryFixedVariant: Palette.minuit700,
    error: Palette.corail300,
    onError: Palette.corail900,
    errorContainer: Palette.corail900,
    onErrorContainer: Palette.corail100,
    surface: Palette.minuit900,
    onSurface: Palette.creme,
    surfaceDim: Palette.minuit950,
    surfaceBright: Palette.minuit700,
    surfaceContainerLowest: Palette.minuit925,
    surfaceContainerLow: Palette.minuit850,
    surfaceContainer: Palette.minuit800,
    surfaceContainerHigh: Palette.minuit750,
    surfaceContainerHighest: Palette.minuit700,
    onSurfaceVariant: Palette.cremeMuted,
    outline: Palette.minuit400,
    outlineVariant: Palette.minuit600,
    shadow: Palette.black,
    scrim: Palette.black,
    inverseSurface: Palette.creme,
    onInverseSurface: Palette.minuit,
    inversePrimary: Palette.lanterne700,
    surfaceTint: Colors.transparent,
  );
}
