// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// The countries at `lat`, `lon` and within 1 km of it: the point and 16
/// points on circles of 500 m and 1 km around it, as the server reads a
/// border (`lunaway_domain::enforcement::near_country`).
CountriesAround countriesAround({required double lat, required double lon}) =>
    RustLib.instance.api.crateApiCountryCountriesAround(lat: lat, lon: lon);

/// The rules table compiled into the app: what it applies before the API
/// has sent its own, or offline.
EmbeddedRules embeddedRules() => RustLib.instance.api.crateApiCountryEmbeddedRules();

/// The countries at a position and around it.
class CountriesAround {
  /// ISO 3166-1 alpha-2 of the country the position lies in; `None` at
  /// sea or outside every boundary.
  final String? at;

  /// Every country within [`BORDER_MARGIN_M`] of the position, the one it
  /// lies in included, without repeats.
  final List<String> near;

  const CountriesAround({this.at, required this.near});

  @override
  int get hashCode => at.hashCode ^ near.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CountriesAround &&
          runtimeType == other.runtimeType &&
          at == other.at &&
          near == other.near;
}

/// One line of the rules table.
class CountryMode {
  /// ISO 3166-1 alpha-2.
  final String country;

  /// `off`, `off_while_driving`, `zones` or `exact`.
  final String mode;

  const CountryMode({required this.country, required this.mode});

  @override
  int get hashCode => country.hashCode ^ mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CountryMode &&
          runtimeType == other.runtimeType &&
          country == other.country &&
          mode == other.mode;
}

/// The rules table the app was built with.
class EmbeddedRules {
  /// The table's version (`EnforcementRules.version` of the API).
  final int version;

  /// When it was last checked against its sources.
  final String reviewedOn;

  /// Each country named; any other is off.
  final List<CountryMode> countries;

  const EmbeddedRules({required this.version, required this.reviewedOn, required this.countries});

  @override
  int get hashCode => version.hashCode ^ reviewedOn.hashCode ^ countries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbeddedRules &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          reviewedOn == other.reviewedOn &&
          countries == other.countries;
}
