// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `invalid_route`, `no_such_route`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `default`

/// The settings the app starts with.
GuidanceSettings defaultGuidanceSettings() =>
    RustLib.instance.api.crateApiEngineDefaultGuidanceSettings();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Guidance>>
abstract class Guidance implements RustOpaqueInterface {
  /// Where the route, from `from_m` metres from its start onwards, meets
  /// each of `events`, in driving order. A line counts when the route
  /// follows it within `line_tolerance_m` (the server's corridor rule:
  /// along a road, not across it; one way only when it is directed); a
  /// point, when the route passes within `point_tolerance_m` of it.
  List<EventHit> eventsAhead({
    required double fromM,
    required List<EventShape> events,
    required double lineToleranceM,
    required double pointToleranceM,
  });

  /// Guidance along route `route_index` of `osrm_json`, the `osrmJson`
  /// field of the API's answer.
  ///
  /// # Errors
  ///
  /// [`GuidanceError`] when the answer cannot be read or has no such route.
  factory Guidance({
    required String osrmJson,
    required int routeIndex,
    required GuidanceSettings settings,
  }) => RustLib.instance.api.crateApiEngineGuidanceNew(
    osrmJson: osrmJson,
    routeIndex: routeIndex,
    settings: settings,
  );

  /// The route's length, metres, as the router measured it.
  double get routeLengthM;

  /// How many steps the route has.
  int get stepCount;

  /// The guidance after `fix`.
  GuidanceState update({required Fix fix});
}

/// What the banner shows.
class Banner {
  /// The main line: the road to take, or what to do.
  final String primary;

  /// A second line, when the router gave one.
  final String? secondary;

  /// The maneuver, as the OSRM format names it (`turn`, `roundabout`,
  /// `arrive`...).
  final String? maneuverType;

  /// Its direction (`left`, `slight right`, `uturn`...).
  final String? modifier;

  /// The exit of a roundabout, degrees, when the router gave it.
  final int? roundaboutExitDegrees;

  /// The lanes, when the router gave them.
  final List<Lane> lanes;

  const Banner({
    required this.primary,
    this.secondary,
    this.maneuverType,
    this.modifier,
    this.roundaboutExitDegrees,
    required this.lanes,
  });

  @override
  int get hashCode =>
      primary.hashCode ^
      secondary.hashCode ^
      maneuverType.hashCode ^
      modifier.hashCode ^
      roundaboutExitDegrees.hashCode ^
      lanes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Banner &&
          runtimeType == other.runtimeType &&
          primary == other.primary &&
          secondary == other.secondary &&
          maneuverType == other.maneuverType &&
          modifier == other.modifier &&
          roundaboutExitDegrees == other.roundaboutExitDegrees &&
          lanes == other.lanes;
}

/// Where the route ahead drives through an event.
class EventHit {
  /// The event.
  final String id;

  /// Metres from the start of the route where the route enters it.
  final double startM;

  /// Metres from the start where it leaves it.
  final double endM;

  /// Where the route enters it, latitude.
  final double lat;

  /// Where the route enters it, longitude.
  final double lon;

  const EventHit({
    required this.id,
    required this.startM,
    required this.endM,
    required this.lat,
    required this.lon,
  });

  @override
  int get hashCode => id.hashCode ^ startM.hashCode ^ endM.hashCode ^ lat.hashCode ^ lon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventHit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startM == other.startM &&
          endM == other.endM &&
          lat == other.lat &&
          lon == other.lon;
}

/// A road event's shape, to check the route against.
class EventShape {
  /// The event's identifier, returned with its hits.
  final String id;

  /// One point, or the line of the road it covers.
  final List<LatLon> points;

  /// The line runs in the direction of traffic it concerns: only a route
  /// that follows it that way meets it (one carriageway of a dual road).
  final bool directed;

  /// For a point: the course of the traffic it concerns, degrees from
  /// north. A route that passes it on another course does not meet it.
  final double? headingDeg;

  /// How far the route's course may stray from [`EventShape::heading_deg`]:
  /// 60 degrees for a reported course, 100 for a cardinal direction.
  final double headingToleranceDeg;

  const EventShape({
    required this.id,
    required this.points,
    required this.directed,
    this.headingDeg,
    required this.headingToleranceDeg,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      points.hashCode ^
      directed.hashCode ^
      headingDeg.hashCode ^
      headingToleranceDeg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventShape &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          points == other.points &&
          directed == other.directed &&
          headingDeg == other.headingDeg &&
          headingToleranceDeg == other.headingToleranceDeg;
}

/// A position fix of the device.
class Fix {
  /// Latitude, WGS 84.
  final double lat;

  /// Longitude, WGS 84.
  final double lon;

  /// Radius of the confidence circle the platform reports, metres.
  final double accuracyM;

  /// Course over ground, degrees from north, when the device moves.
  final double? courseDeg;

  /// Speed over ground, metres per second, when known.
  final double? speedMps;

  /// When the fix was taken, milliseconds since the Unix epoch.
  final PlatformInt64 timestampMs;

  const Fix({
    required this.lat,
    required this.lon,
    required this.accuracyM,
    this.courseDeg,
    this.speedMps,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      lat.hashCode ^
      lon.hashCode ^
      accuracyM.hashCode ^
      courseDeg.hashCode ^
      speedMps.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Fix &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lon == other.lon &&
          accuracyM == other.accuracyM &&
          courseDeg == other.courseDeg &&
          speedMps == other.speedMps &&
          timestampMs == other.timestampMs;
}

/// Why a guidance could not start.
///
/// A kind and a message rather than an enum with data: the bridge turns an
/// enum with fields into a `freezed` class, a dependency the app does not
/// otherwise need.
class GuidanceError implements FrbException {
  /// What went wrong.
  final GuidanceErrorKind kind;

  /// The details, for the log.
  final String message;

  const GuidanceError({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuidanceError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// What went wrong when a guidance started.
enum GuidanceErrorKind {
  /// The route answer could not be read.
  invalidRoute,

  /// The answer holds fewer routes than the index asked for.
  noSuchRoute,
}

/// The tolerances of the guidance.
class GuidanceSettings {
  /// The vehicle is off the route beyond this distance from its line,
  /// metres.
  final double maxDeviationM;

  /// A fix less precise than this, metres, never decides that the vehicle
  /// left the route or passed a maneuver: a fix in an urban canyon or a
  /// tunnel can be 50 m off.
  final int minAccuracyM;

  /// A step ends once the vehicle is this far past its maneuver along the
  /// route, metres: small, so the banner does not lag behind the turn,
  /// and enough that a vehicle waiting at the junction keeps the
  /// maneuver ahead.
  final int maneuverLeftM;

  /// The trip ends this close to the destination, metres.
  final int arrivalM;

  const GuidanceSettings({
    required this.maxDeviationM,
    required this.minAccuracyM,
    required this.maneuverLeftM,
    required this.arrivalM,
  });

  @override
  int get hashCode =>
      maxDeviationM.hashCode ^ minAccuracyM.hashCode ^ maneuverLeftM.hashCode ^ arrivalM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuidanceSettings &&
          runtimeType == other.runtimeType &&
          maxDeviationM == other.maxDeviationM &&
          minAccuracyM == other.minAccuracyM &&
          maneuverLeftM == other.maneuverLeftM &&
          arrivalM == other.arrivalM;
}

/// The guidance after a fix.
class GuidanceState {
  /// Navigating or arrived.
  final GuidanceStatus status;

  /// The vehicle's position on the route, latitude.
  final double snappedLat;

  /// The vehicle's position on the route, longitude.
  final double snappedLon;

  /// The route's heading there, degrees from north.
  final double? courseDeg;

  /// Index of the current step in the route's steps (OSRM order).
  final int stepIndex;

  /// Metres to the next maneuver.
  final double distanceToManeuverM;

  /// Metres to the destination.
  final double distanceRemainingM;

  /// Seconds to the destination, at the router's speeds.
  final double durationRemainingS;

  /// Metres driven along the route: where a warning of the route lies
  /// ahead is its distance from the start minus this.
  final double distanceAlongM;

  /// Distance from the route line when the vehicle has left the route,
  /// metres; none while it follows it.
  final double? offRouteM;

  /// What the banner shows now.
  final Banner? banner;

  /// The latest instruction to speak; the same one comes back until the
  /// next is due.
  final Utterance? utterance;

  /// The speed limit where the vehicle is, km/h, when the map has it.
  final double? speedLimitKmh;

  const GuidanceState({
    required this.status,
    required this.snappedLat,
    required this.snappedLon,
    this.courseDeg,
    required this.stepIndex,
    required this.distanceToManeuverM,
    required this.distanceRemainingM,
    required this.durationRemainingS,
    required this.distanceAlongM,
    this.offRouteM,
    this.banner,
    this.utterance,
    this.speedLimitKmh,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      snappedLat.hashCode ^
      snappedLon.hashCode ^
      courseDeg.hashCode ^
      stepIndex.hashCode ^
      distanceToManeuverM.hashCode ^
      distanceRemainingM.hashCode ^
      durationRemainingS.hashCode ^
      distanceAlongM.hashCode ^
      offRouteM.hashCode ^
      banner.hashCode ^
      utterance.hashCode ^
      speedLimitKmh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuidanceState &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          snappedLat == other.snappedLat &&
          snappedLon == other.snappedLon &&
          courseDeg == other.courseDeg &&
          stepIndex == other.stepIndex &&
          distanceToManeuverM == other.distanceToManeuverM &&
          distanceRemainingM == other.distanceRemainingM &&
          durationRemainingS == other.durationRemainingS &&
          distanceAlongM == other.distanceAlongM &&
          offRouteM == other.offRouteM &&
          banner == other.banner &&
          utterance == other.utterance &&
          speedLimitKmh == other.speedLimitKmh;
}

/// Where the trip stands.
enum GuidanceStatus {
  /// On the way.
  navigating,

  /// At the destination.
  arrived,
}

/// One lane at the next intersection.
class Lane {
  /// The directions it allows (`straight`, `left`, `slight right`...).
  final List<String> directions;

  /// Whether it leads where the route goes.
  final bool active;

  const Lane({required this.directions, required this.active});

  @override
  int get hashCode => directions.hashCode ^ active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lane &&
          runtimeType == other.runtimeType &&
          directions == other.directions &&
          active == other.active;
}

/// A point.
class LatLon {
  /// Latitude, WGS 84.
  final double lat;

  /// Longitude, WGS 84.
  final double lon;

  const LatLon({required this.lat, required this.lon});

  @override
  int get hashCode => lat.hashCode ^ lon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LatLon && runtimeType == other.runtimeType && lat == other.lat && lon == other.lon;
}

/// An instruction to speak.
class Utterance {
  /// Stable for one instruction of one route: speak each once.
  final String id;

  /// Plain text.
  final String text;

  /// The same as SSML, when the router gave it.
  final String? ssml;

  const Utterance({required this.id, required this.text, this.ssml});

  @override
  int get hashCode => id.hashCode ^ text.hashCode ^ ssml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Utterance &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          ssml == other.ssml;
}
