// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/country.dart';
import 'api/engine.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1834818909;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'lunaway_nav',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  List<EventHit> crateApiEngineGuidanceEventsAhead({
    required Guidance that,
    required double fromM,
    required List<EventShape> events,
    required double lineToleranceM,
    required double pointToleranceM,
  });

  Guidance crateApiEngineGuidanceNew({
    required String osrmJson,
    required int routeIndex,
    required GuidanceSettings settings,
  });

  double crateApiEngineGuidanceRouteLengthM({required Guidance that});

  int crateApiEngineGuidanceStepCount({required Guidance that});

  GuidanceState crateApiEngineGuidanceUpdate({required Guidance that, required Fix fix});

  CountriesAround crateApiCountryCountriesAround({required double lat, required double lon});

  GuidanceSettings crateApiEngineDefaultGuidanceSettings();

  EmbeddedRules crateApiCountryEmbeddedRules();

  Future<GuidanceSettings> crateApiEngineGuidanceSettingsDefault();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Guidance;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Guidance;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GuidancePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<EventHit> crateApiEngineGuidanceEventsAhead({
    required Guidance that,
    required double fromM,
    required List<EventShape> events,
    required double lineToleranceM,
    required double pointToleranceM,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
            that,
            serializer,
          );
          sse_encode_f_64(fromM, serializer);
          sse_encode_list_event_shape(events, serializer);
          sse_encode_f_64(lineToleranceM, serializer);
          sse_encode_f_64(pointToleranceM, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_event_hit, decodeErrorData: null),
        constMeta: kCrateApiEngineGuidanceEventsAheadConstMeta,
        argValues: [that, fromM, events, lineToleranceM, pointToleranceM],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGuidanceEventsAheadConstMeta => const TaskConstMeta(
    debugName: "Guidance_events_ahead",
    argNames: ["that", "fromM", "events", "lineToleranceM", "pointToleranceM"],
  );

  @override
  Guidance crateApiEngineGuidanceNew({
    required String osrmJson,
    required int routeIndex,
    required GuidanceSettings settings,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(osrmJson, serializer);
          sse_encode_u_32(routeIndex, serializer);
          sse_encode_box_autoadd_guidance_settings(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance,
          decodeErrorData: sse_decode_guidance_error,
        ),
        constMeta: kCrateApiEngineGuidanceNewConstMeta,
        argValues: [osrmJson, routeIndex, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGuidanceNewConstMeta => const TaskConstMeta(
    debugName: "Guidance_new",
    argNames: ["osrmJson", "routeIndex", "settings"],
  );

  @override
  double crateApiEngineGuidanceRouteLengthM({required Guidance that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_f_64, decodeErrorData: null),
        constMeta: kCrateApiEngineGuidanceRouteLengthMConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGuidanceRouteLengthMConstMeta =>
      const TaskConstMeta(debugName: "Guidance_route_length_m", argNames: ["that"]);

  @override
  int crateApiEngineGuidanceStepCount({required Guidance that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_u_32, decodeErrorData: null),
        constMeta: kCrateApiEngineGuidanceStepCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGuidanceStepCountConstMeta =>
      const TaskConstMeta(debugName: "Guidance_step_count", argNames: ["that"]);

  @override
  GuidanceState crateApiEngineGuidanceUpdate({required Guidance that, required Fix fix}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
            that,
            serializer,
          );
          sse_encode_box_autoadd_fix(fix, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_guidance_state, decodeErrorData: null),
        constMeta: kCrateApiEngineGuidanceUpdateConstMeta,
        argValues: [that, fix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGuidanceUpdateConstMeta =>
      const TaskConstMeta(debugName: "Guidance_update", argNames: ["that", "fix"]);

  @override
  CountriesAround crateApiCountryCountriesAround({required double lat, required double lon}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(lat, serializer);
          sse_encode_f_64(lon, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_countries_around, decodeErrorData: null),
        constMeta: kCrateApiCountryCountriesAroundConstMeta,
        argValues: [lat, lon],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCountryCountriesAroundConstMeta =>
      const TaskConstMeta(debugName: "countries_around", argNames: ["lat", "lon"]);

  @override
  GuidanceSettings crateApiEngineDefaultGuidanceSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_guidance_settings, decodeErrorData: null),
        constMeta: kCrateApiEngineDefaultGuidanceSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineDefaultGuidanceSettingsConstMeta =>
      const TaskConstMeta(debugName: "default_guidance_settings", argNames: []);

  @override
  EmbeddedRules crateApiCountryEmbeddedRules() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_embedded_rules, decodeErrorData: null),
        constMeta: kCrateApiCountryEmbeddedRulesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCountryEmbeddedRulesConstMeta =>
      const TaskConstMeta(debugName: "embedded_rules", argNames: []);

  @override
  Future<GuidanceSettings> crateApiEngineGuidanceSettingsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_guidance_settings, decodeErrorData: null),
        constMeta: kCrateApiEngineGuidanceSettingsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineGuidanceSettingsDefaultConstMeta =>
      const TaskConstMeta(debugName: "guidance_settings_default", argNames: []);

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Guidance => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Guidance => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance;

  @protected
  Guidance
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GuidanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Guidance
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GuidanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Guidance
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GuidanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Guidance dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GuidanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Banner dco_decode_banner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Banner(
      primary: dco_decode_String(arr[0]),
      secondary: dco_decode_opt_String(arr[1]),
      maneuverType: dco_decode_opt_String(arr[2]),
      modifier: dco_decode_opt_String(arr[3]),
      roundaboutExitDegrees: dco_decode_opt_box_autoadd_u_16(arr[4]),
      lanes: dco_decode_list_lane(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Banner dco_decode_box_autoadd_banner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_banner(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Fix dco_decode_box_autoadd_fix(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fix(raw);
  }

  @protected
  GuidanceSettings dco_decode_box_autoadd_guidance_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_guidance_settings(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Utterance dco_decode_box_autoadd_utterance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_utterance(raw);
  }

  @protected
  CountriesAround dco_decode_countries_around(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CountriesAround(at: dco_decode_opt_String(arr[0]), near: dco_decode_list_String(arr[1]));
  }

  @protected
  CountryMode dco_decode_country_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CountryMode(country: dco_decode_String(arr[0]), mode: dco_decode_String(arr[1]));
  }

  @protected
  EmbeddedRules dco_decode_embedded_rules(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EmbeddedRules(
      version: dco_decode_u_32(arr[0]),
      reviewedOn: dco_decode_String(arr[1]),
      countries: dco_decode_list_country_mode(arr[2]),
    );
  }

  @protected
  EventHit dco_decode_event_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return EventHit(
      id: dco_decode_String(arr[0]),
      startM: dco_decode_f_64(arr[1]),
      endM: dco_decode_f_64(arr[2]),
      lat: dco_decode_f_64(arr[3]),
      lon: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  EventShape dco_decode_event_shape(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return EventShape(
      id: dco_decode_String(arr[0]),
      points: dco_decode_list_lat_lon(arr[1]),
      directed: dco_decode_bool(arr[2]),
      headingDeg: dco_decode_opt_box_autoadd_f_64(arr[3]),
      headingToleranceDeg: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Fix dco_decode_fix(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Fix(
      lat: dco_decode_f_64(arr[0]),
      lon: dco_decode_f_64(arr[1]),
      accuracyM: dco_decode_f_64(arr[2]),
      courseDeg: dco_decode_opt_box_autoadd_f_64(arr[3]),
      speedMps: dco_decode_opt_box_autoadd_f_64(arr[4]),
      timestampMs: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  GuidanceError dco_decode_guidance_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GuidanceError(
      kind: dco_decode_guidance_error_kind(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  GuidanceErrorKind dco_decode_guidance_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GuidanceErrorKind.values[raw as int];
  }

  @protected
  GuidanceSettings dco_decode_guidance_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GuidanceSettings(
      maxDeviationM: dco_decode_f_64(arr[0]),
      minAccuracyM: dco_decode_u_16(arr[1]),
      maneuverReachedM: dco_decode_u_16(arr[2]),
      arrivalM: dco_decode_u_16(arr[3]),
    );
  }

  @protected
  GuidanceState dco_decode_guidance_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13) throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return GuidanceState(
      status: dco_decode_guidance_status(arr[0]),
      snappedLat: dco_decode_f_64(arr[1]),
      snappedLon: dco_decode_f_64(arr[2]),
      courseDeg: dco_decode_opt_box_autoadd_f_64(arr[3]),
      stepIndex: dco_decode_u_32(arr[4]),
      distanceToManeuverM: dco_decode_f_64(arr[5]),
      distanceRemainingM: dco_decode_f_64(arr[6]),
      durationRemainingS: dco_decode_f_64(arr[7]),
      distanceAlongM: dco_decode_f_64(arr[8]),
      offRouteM: dco_decode_opt_box_autoadd_f_64(arr[9]),
      banner: dco_decode_opt_box_autoadd_banner(arr[10]),
      utterance: dco_decode_opt_box_autoadd_utterance(arr[11]),
      speedLimitKmh: dco_decode_opt_box_autoadd_f_64(arr[12]),
    );
  }

  @protected
  GuidanceStatus dco_decode_guidance_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GuidanceStatus.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Lane dco_decode_lane(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Lane(directions: dco_decode_list_String(arr[0]), active: dco_decode_bool(arr[1]));
  }

  @protected
  LatLon dco_decode_lat_lon(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LatLon(lat: dco_decode_f_64(arr[0]), lon: dco_decode_f_64(arr[1]));
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CountryMode> dco_decode_list_country_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_country_mode).toList();
  }

  @protected
  List<EventHit> dco_decode_list_event_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_event_hit).toList();
  }

  @protected
  List<EventShape> dco_decode_list_event_shape(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_event_shape).toList();
  }

  @protected
  List<Lane> dco_decode_list_lane(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lane).toList();
  }

  @protected
  List<LatLon> dco_decode_list_lat_lon(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lat_lon).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Banner? dco_decode_opt_box_autoadd_banner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_banner(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  Utterance? dco_decode_opt_box_autoadd_utterance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_utterance(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Utterance dco_decode_utterance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Utterance(
      id: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      ssml: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  Guidance
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GuidanceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Guidance
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GuidanceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Guidance
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GuidanceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Guidance sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return GuidanceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Banner sse_decode_banner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_primary = sse_decode_String(deserializer);
    var var_secondary = sse_decode_opt_String(deserializer);
    var var_maneuverType = sse_decode_opt_String(deserializer);
    var var_modifier = sse_decode_opt_String(deserializer);
    var var_roundaboutExitDegrees = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_lanes = sse_decode_list_lane(deserializer);
    return Banner(
      primary: var_primary,
      secondary: var_secondary,
      maneuverType: var_maneuverType,
      modifier: var_modifier,
      roundaboutExitDegrees: var_roundaboutExitDegrees,
      lanes: var_lanes,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Banner sse_decode_box_autoadd_banner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_banner(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  Fix sse_decode_box_autoadd_fix(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fix(deserializer));
  }

  @protected
  GuidanceSettings sse_decode_box_autoadd_guidance_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_guidance_settings(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  Utterance sse_decode_box_autoadd_utterance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_utterance(deserializer));
  }

  @protected
  CountriesAround sse_decode_countries_around(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_at = sse_decode_opt_String(deserializer);
    var var_near = sse_decode_list_String(deserializer);
    return CountriesAround(at: var_at, near: var_near);
  }

  @protected
  CountryMode sse_decode_country_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_country = sse_decode_String(deserializer);
    var var_mode = sse_decode_String(deserializer);
    return CountryMode(country: var_country, mode: var_mode);
  }

  @protected
  EmbeddedRules sse_decode_embedded_rules(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_32(deserializer);
    var var_reviewedOn = sse_decode_String(deserializer);
    var var_countries = sse_decode_list_country_mode(deserializer);
    return EmbeddedRules(
      version: var_version,
      reviewedOn: var_reviewedOn,
      countries: var_countries,
    );
  }

  @protected
  EventHit sse_decode_event_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_startM = sse_decode_f_64(deserializer);
    var var_endM = sse_decode_f_64(deserializer);
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    return EventHit(id: var_id, startM: var_startM, endM: var_endM, lat: var_lat, lon: var_lon);
  }

  @protected
  EventShape sse_decode_event_shape(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_points = sse_decode_list_lat_lon(deserializer);
    var var_directed = sse_decode_bool(deserializer);
    var var_headingDeg = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_headingToleranceDeg = sse_decode_f_64(deserializer);
    return EventShape(
      id: var_id,
      points: var_points,
      directed: var_directed,
      headingDeg: var_headingDeg,
      headingToleranceDeg: var_headingToleranceDeg,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Fix sse_decode_fix(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    var var_accuracyM = sse_decode_f_64(deserializer);
    var var_courseDeg = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_speedMps = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    return Fix(
      lat: var_lat,
      lon: var_lon,
      accuracyM: var_accuracyM,
      courseDeg: var_courseDeg,
      speedMps: var_speedMps,
      timestampMs: var_timestampMs,
    );
  }

  @protected
  GuidanceError sse_decode_guidance_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_guidance_error_kind(deserializer);
    var var_message = sse_decode_String(deserializer);
    return GuidanceError(kind: var_kind, message: var_message);
  }

  @protected
  GuidanceErrorKind sse_decode_guidance_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GuidanceErrorKind.values[inner];
  }

  @protected
  GuidanceSettings sse_decode_guidance_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_maxDeviationM = sse_decode_f_64(deserializer);
    var var_minAccuracyM = sse_decode_u_16(deserializer);
    var var_maneuverReachedM = sse_decode_u_16(deserializer);
    var var_arrivalM = sse_decode_u_16(deserializer);
    return GuidanceSettings(
      maxDeviationM: var_maxDeviationM,
      minAccuracyM: var_minAccuracyM,
      maneuverReachedM: var_maneuverReachedM,
      arrivalM: var_arrivalM,
    );
  }

  @protected
  GuidanceState sse_decode_guidance_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_guidance_status(deserializer);
    var var_snappedLat = sse_decode_f_64(deserializer);
    var var_snappedLon = sse_decode_f_64(deserializer);
    var var_courseDeg = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_stepIndex = sse_decode_u_32(deserializer);
    var var_distanceToManeuverM = sse_decode_f_64(deserializer);
    var var_distanceRemainingM = sse_decode_f_64(deserializer);
    var var_durationRemainingS = sse_decode_f_64(deserializer);
    var var_distanceAlongM = sse_decode_f_64(deserializer);
    var var_offRouteM = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_banner = sse_decode_opt_box_autoadd_banner(deserializer);
    var var_utterance = sse_decode_opt_box_autoadd_utterance(deserializer);
    var var_speedLimitKmh = sse_decode_opt_box_autoadd_f_64(deserializer);
    return GuidanceState(
      status: var_status,
      snappedLat: var_snappedLat,
      snappedLon: var_snappedLon,
      courseDeg: var_courseDeg,
      stepIndex: var_stepIndex,
      distanceToManeuverM: var_distanceToManeuverM,
      distanceRemainingM: var_distanceRemainingM,
      durationRemainingS: var_durationRemainingS,
      distanceAlongM: var_distanceAlongM,
      offRouteM: var_offRouteM,
      banner: var_banner,
      utterance: var_utterance,
      speedLimitKmh: var_speedLimitKmh,
    );
  }

  @protected
  GuidanceStatus sse_decode_guidance_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GuidanceStatus.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Lane sse_decode_lane(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_directions = sse_decode_list_String(deserializer);
    var var_active = sse_decode_bool(deserializer);
    return Lane(directions: var_directions, active: var_active);
  }

  @protected
  LatLon sse_decode_lat_lon(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lat = sse_decode_f_64(deserializer);
    var var_lon = sse_decode_f_64(deserializer);
    return LatLon(lat: var_lat, lon: var_lon);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CountryMode> sse_decode_list_country_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CountryMode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_country_mode(deserializer));
    }
    return ans_;
  }

  @protected
  List<EventHit> sse_decode_list_event_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EventHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_event_hit(deserializer));
    }
    return ans_;
  }

  @protected
  List<EventShape> sse_decode_list_event_shape(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EventShape>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_event_shape(deserializer));
    }
    return ans_;
  }

  @protected
  List<Lane> sse_decode_list_lane(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Lane>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lane(deserializer));
    }
    return ans_;
  }

  @protected
  List<LatLon> sse_decode_list_lat_lon(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LatLon>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lat_lon(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Banner? sse_decode_opt_box_autoadd_banner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_banner(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Utterance? sse_decode_opt_box_autoadd_utterance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_utterance(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  Utterance sse_decode_utterance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_ssml = sse_decode_opt_String(deserializer);
    return Utterance(id: var_id, text: var_text, ssml: var_ssml);
  }

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as GuidanceImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as GuidanceImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as GuidanceImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize((self as GuidanceImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_banner(Banner self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.primary, serializer);
    sse_encode_opt_String(self.secondary, serializer);
    sse_encode_opt_String(self.maneuverType, serializer);
    sse_encode_opt_String(self.modifier, serializer);
    sse_encode_opt_box_autoadd_u_16(self.roundaboutExitDegrees, serializer);
    sse_encode_list_lane(self.lanes, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_banner(Banner self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_banner(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_fix(Fix self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fix(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_guidance_settings(GuidanceSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_guidance_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_utterance(Utterance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_utterance(self, serializer);
  }

  @protected
  void sse_encode_countries_around(CountriesAround self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.at, serializer);
    sse_encode_list_String(self.near, serializer);
  }

  @protected
  void sse_encode_country_mode(CountryMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.country, serializer);
    sse_encode_String(self.mode, serializer);
  }

  @protected
  void sse_encode_embedded_rules(EmbeddedRules self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.version, serializer);
    sse_encode_String(self.reviewedOn, serializer);
    sse_encode_list_country_mode(self.countries, serializer);
  }

  @protected
  void sse_encode_event_hit(EventHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_f_64(self.startM, serializer);
    sse_encode_f_64(self.endM, serializer);
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
  }

  @protected
  void sse_encode_event_shape(EventShape self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_list_lat_lon(self.points, serializer);
    sse_encode_bool(self.directed, serializer);
    sse_encode_opt_box_autoadd_f_64(self.headingDeg, serializer);
    sse_encode_f_64(self.headingToleranceDeg, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fix(Fix self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
    sse_encode_f_64(self.accuracyM, serializer);
    sse_encode_opt_box_autoadd_f_64(self.courseDeg, serializer);
    sse_encode_opt_box_autoadd_f_64(self.speedMps, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
  }

  @protected
  void sse_encode_guidance_error(GuidanceError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_guidance_error_kind(self.kind, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_guidance_error_kind(GuidanceErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_guidance_settings(GuidanceSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.maxDeviationM, serializer);
    sse_encode_u_16(self.minAccuracyM, serializer);
    sse_encode_u_16(self.maneuverReachedM, serializer);
    sse_encode_u_16(self.arrivalM, serializer);
  }

  @protected
  void sse_encode_guidance_state(GuidanceState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_guidance_status(self.status, serializer);
    sse_encode_f_64(self.snappedLat, serializer);
    sse_encode_f_64(self.snappedLon, serializer);
    sse_encode_opt_box_autoadd_f_64(self.courseDeg, serializer);
    sse_encode_u_32(self.stepIndex, serializer);
    sse_encode_f_64(self.distanceToManeuverM, serializer);
    sse_encode_f_64(self.distanceRemainingM, serializer);
    sse_encode_f_64(self.durationRemainingS, serializer);
    sse_encode_f_64(self.distanceAlongM, serializer);
    sse_encode_opt_box_autoadd_f_64(self.offRouteM, serializer);
    sse_encode_opt_box_autoadd_banner(self.banner, serializer);
    sse_encode_opt_box_autoadd_utterance(self.utterance, serializer);
    sse_encode_opt_box_autoadd_f_64(self.speedLimitKmh, serializer);
  }

  @protected
  void sse_encode_guidance_status(GuidanceStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_lane(Lane self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.directions, serializer);
    sse_encode_bool(self.active, serializer);
  }

  @protected
  void sse_encode_lat_lon(LatLon self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lon, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_country_mode(List<CountryMode> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_country_mode(item, serializer);
    }
  }

  @protected
  void sse_encode_list_event_hit(List<EventHit> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_event_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_event_shape(List<EventShape> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_event_shape(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lane(List<Lane> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lane(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lat_lon(List<LatLon> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lat_lon(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_banner(Banner? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_banner(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_utterance(Utterance? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_utterance(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_utterance(Utterance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_opt_String(self.ssml, serializer);
  }
}

@sealed
class GuidanceImpl extends RustOpaque implements Guidance {
  // Not to be used by end users
  GuidanceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  GuidanceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_Guidance,
    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_Guidance,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_GuidancePtr,
  );

  /// Where the route, from `from_m` metres from its start onwards, meets
  /// each of `events`, in driving order. A line counts when the route
  /// follows it within `line_tolerance_m` (the server's corridor rule:
  /// along a road, not across it; one way only when it is directed); a
  /// point, when the route passes within `point_tolerance_m` of it.
  List<EventHit> eventsAhead({
    required double fromM,
    required List<EventShape> events,
    required double lineToleranceM,
    required double pointToleranceM,
  }) => RustLib.instance.api.crateApiEngineGuidanceEventsAhead(
    that: this,
    fromM: fromM,
    events: events,
    lineToleranceM: lineToleranceM,
    pointToleranceM: pointToleranceM,
  );

  /// The route's length, metres, as the router measured it.
  double get routeLengthM => RustLib.instance.api.crateApiEngineGuidanceRouteLengthM(that: this);

  /// How many steps the route has.
  int get stepCount => RustLib.instance.api.crateApiEngineGuidanceStepCount(that: this);

  /// The guidance after `fix`.
  GuidanceState update({required Fix fix}) =>
      RustLib.instance.api.crateApiEngineGuidanceUpdate(that: this, fix: fix);
}
