// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GuidancePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidancePtr;

  @protected
  Guidance
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  );

  @protected
  Guidance
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  );

  @protected
  Guidance
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  );

  @protected
  Guidance dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Banner dco_decode_banner(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Banner dco_decode_box_autoadd_banner(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  Fix dco_decode_box_autoadd_fix(dynamic raw);

  @protected
  GuidanceSettings dco_decode_box_autoadd_guidance_settings(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  Utterance dco_decode_box_autoadd_utterance(dynamic raw);

  @protected
  EventHit dco_decode_event_hit(dynamic raw);

  @protected
  EventShape dco_decode_event_shape(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Fix dco_decode_fix(dynamic raw);

  @protected
  GuidanceError dco_decode_guidance_error(dynamic raw);

  @protected
  GuidanceErrorKind dco_decode_guidance_error_kind(dynamic raw);

  @protected
  GuidanceSettings dco_decode_guidance_settings(dynamic raw);

  @protected
  GuidanceState dco_decode_guidance_state(dynamic raw);

  @protected
  GuidanceStatus dco_decode_guidance_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Lane dco_decode_lane(dynamic raw);

  @protected
  LatLon dco_decode_lat_lon(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<EventHit> dco_decode_list_event_hit(dynamic raw);

  @protected
  List<EventShape> dco_decode_list_event_shape(dynamic raw);

  @protected
  List<Lane> dco_decode_list_lane(dynamic raw);

  @protected
  List<LatLon> dco_decode_list_lat_lon(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Banner? dco_decode_opt_box_autoadd_banner(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  Utterance? dco_decode_opt_box_autoadd_utterance(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Utterance dco_decode_utterance(dynamic raw);

  @protected
  Guidance
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  );

  @protected
  Guidance
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  );

  @protected
  Guidance
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  );

  @protected
  Guidance sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Banner sse_decode_banner(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Banner sse_decode_box_autoadd_banner(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  Fix sse_decode_box_autoadd_fix(SseDeserializer deserializer);

  @protected
  GuidanceSettings sse_decode_box_autoadd_guidance_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  Utterance sse_decode_box_autoadd_utterance(SseDeserializer deserializer);

  @protected
  EventHit sse_decode_event_hit(SseDeserializer deserializer);

  @protected
  EventShape sse_decode_event_shape(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Fix sse_decode_fix(SseDeserializer deserializer);

  @protected
  GuidanceError sse_decode_guidance_error(SseDeserializer deserializer);

  @protected
  GuidanceErrorKind sse_decode_guidance_error_kind(SseDeserializer deserializer);

  @protected
  GuidanceSettings sse_decode_guidance_settings(SseDeserializer deserializer);

  @protected
  GuidanceState sse_decode_guidance_state(SseDeserializer deserializer);

  @protected
  GuidanceStatus sse_decode_guidance_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Lane sse_decode_lane(SseDeserializer deserializer);

  @protected
  LatLon sse_decode_lat_lon(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<EventHit> sse_decode_list_event_hit(SseDeserializer deserializer);

  @protected
  List<EventShape> sse_decode_list_event_shape(SseDeserializer deserializer);

  @protected
  List<Lane> sse_decode_list_lane(SseDeserializer deserializer);

  @protected
  List<LatLon> sse_decode_list_lat_lon(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Banner? sse_decode_opt_box_autoadd_banner(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  Utterance? sse_decode_opt_box_autoadd_utterance(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Utterance sse_decode_utterance(SseDeserializer deserializer);

  @protected
  void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    Guidance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_banner(Banner self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_banner(Banner self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fix(Fix self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_guidance_settings(GuidanceSettings self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_utterance(Utterance self, SseSerializer serializer);

  @protected
  void sse_encode_event_hit(EventHit self, SseSerializer serializer);

  @protected
  void sse_encode_event_shape(EventShape self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fix(Fix self, SseSerializer serializer);

  @protected
  void sse_encode_guidance_error(GuidanceError self, SseSerializer serializer);

  @protected
  void sse_encode_guidance_error_kind(GuidanceErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_guidance_settings(GuidanceSettings self, SseSerializer serializer);

  @protected
  void sse_encode_guidance_state(GuidanceState self, SseSerializer serializer);

  @protected
  void sse_encode_guidance_status(GuidanceStatus self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_lane(Lane self, SseSerializer serializer);

  @protected
  void sse_encode_lat_lon(LatLon self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_event_hit(List<EventHit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_event_shape(List<EventShape> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lane(List<Lane> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lat_lon(List<LatLon> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_banner(Banner? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_utterance(Utterance? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_utterance(Utterance self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidancePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_lunaway_nav_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidancePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidancePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_lunaway_nav_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidance =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGuidancePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
